name: vdmc
author: Ryan Gonzalez
version: 0.1.0
description: Project description goes here
dependencies:
  js: any
  vue: ^0.4.0
dependency_overrides:
  scopify:
    path: /code/scopify
  vue:
    path: /code/vuedart/vue
dev_dependencies:
  build_runner: any
  build_web_compilers: any
  http: any
  path: any
