name: vdmc_playground
author: Ryan Gonzalez
version: 0.1.0
description: Project description goes here
dependencies:
  vdmc: any
  vue: ^0.4.0
dependency_overrides:
  vdmc:
    path: ../vdmc
  vue:
    path: ../../vuedart/vue
dev_dependencies:
  build_runner: any
  build_web_compilers: any
